### ISSUE TITLE
Custom properties not being read from kitchen.yml

### ISSUE THREAD

**Issue by bender-the-greatest** [chef-partners/kitchen-vra#30]
### Versions:

* Version of kitchen-vra: 2.6.0
* Version of test-kitchen: 1.16.0
* Version of chef: 12.21.26

### Platform Details

* Version of vRA: 7.2
* Version of ESXi: 6.5

### Scenario:
Extra parameters are not being applied to the VM request when I run `kitchen create`. Not sure if it's relevant but I am specifying an alternate kitchen file by setting `$env:KITCHEN_YAML`. Test Kitchen is being executed from Powershell 5.1 on Windows 10.

### Steps to Reproduce:
Here is the platform portion of my kitchen file in regards to setting the custom property values (generalized to remove company specific data but the structure is the same):
```
platforms:
  - name: platform-windows-2012r2
    driver:
      cpus: 2
      memory: 4096
      catalog_name: Windows2012R2
      subtenant_name: 'cloud_dev'
      extra_parameters:
        provider-My.Property.Name:
          type: string
          value: 'Some value goes here'
```

There are about 15 properties i'm setting in this way under `extra_parameters`. It is also unclear whether machine properties need to be nested specially as well.

### Expected Result:
All custom properties I am passing in are recognized.

### Actual Result:
For required properties, the request fails with the error "The data specified within the request is invalid., Field with id My.Property.Name is required." In reality the error is extended with every required property that is not being picked up from my kitchen file.
