### ISSUE TITLE
separate vra / machine credentials

### ISSUE THREAD

**Issue by theballdredge** [chef-partners/kitchen-vra#9]
when creating vms using vRA it appears that there is no way to specify the username used to connect to the created vm.

sometimes those users are not the same, and in those cases it is necessary to connect to a kitchen machine as another user.

**Comment by adamleff** [comment]
The username to use when connecting to a VM is set in the transport section of the .kitchen.yml and is not specific to the driver used to create the VM.

Just update your .kitchen.yml accordingly:

```yaml
transport:
  username: myuser
```

Or you can set it on a per-platform basis:

```yaml
platforms:
  - name: centos-7
    transport:
      username: centosuser
  - name: ubuntu-14.04
    transport:
      username: ubuntuuser
```

There are other transport-specific settings you can use, as well.  Check out the code for each transport plugin here for available config parameters: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb for the SSH transport, for example.
